### ISSUE TITLE
Broken in YouTube Shorts Tab

### ISSUE THREAD

**Issue by Weather-OS** [PoomSmart/Return-YouTube-Dislikes#70]
The dislike and like count show the count of the previous short instead of the current short.

**Comment by PoomSmart** [comment]
How did you know it's really the like/dislike data from the previous short?

**Comment by PoomSmart** [comment]
Should be fixed in v1.11.18

**Comment by Weather-OS** [comment]
Still broken
![2A7EF02A-6852-46D9-B95D-FEA4632F9A18](https://github.com/PoomSmart/Return-YouTube-Dislikes/assets/84678467/3fdcc4f9-b168-4f3f-b53d-b8be1bcf7dcd)

**Comment by PoomSmart** [comment]
How do you know it's really from the previous short?

**Comment by Weather-OS** [comment]
In that instance, the previous short had like 253 likes or something so it would make sense for it to have 3 dislikes.

**Comment by PoomSmart** [comment]
@Weather-OS Can you give me the link to that Shorts?

**Comment by PoomSmart** [comment]
By the way, it makes total sense for the like/dislike ratio to be like that because not everyone has Return YouTube Dislike (whether it's a browser extension, hacked app or this tweak) installed. If the video author doesn't explicitly contribute the actual vote data to RYD server, then the dislike number you see is the total number of dislikes from RYD users.

For example, this video: https://www.youtube.com/watch?v=oE8hAQie8fw

Like: 56K
Dislike: 394

For a MV such as this the number of dislikes should be in thousands if not more.

**Comment by Weather-OS** [comment]
![36AEB725-DF6E-4B33-A797-30679130D2E4](https://github.com/user-attachments/assets/b64214eb-02dc-4931-aec2-91afbcc8711e)

**Comment by PoomSmart** [comment]
Sorry but I can't reproduce that issue. Besides the reason I wrote above that would already refute your confirmation, I verified that the API returns the correct vote data and what current short is displayed using the video ID. If you think this issue is legitimate, open a new issue stating the exact shorts that you found the vote data to be shifting.
